### ISSUE TITLE
No binary?

### ISSUE THREAD

**Issue by Wowfunhappy** [rtiangha/SiEd-Dana#1]
Hi! There doesn't appear to be a precompiled src binary anywhere, despite the readme saying to download one. Did you forget to include it?

**Comment by rtiangha** [comment]
Should be on the releases link:

https://github.com/rtiangha/SiEd-Dana/releases

Note that there's a known issue with the Dana's screen rotate feature 
where things might not get rendered correctly or get rendered off screen 
if you rotate the Dana's screen to work in Tall mode rather than the 
default Wide mode. That's because there's a lot of hard-coded screen 
dimension values still in the code, especially when it comes to 
rendering the status bar at the bottom of the screen; should be fixed by 
dynamically calculating those dimensions at run time. For now, I just 
changed the hard-coded limits to match the Dana's resolution values. I'm 
still working through making things more robust, but real life got in 
the way.

**Comment by rtiangha** [comment]
Ah, I see what you mean now. I fixed the link in the README to point to the updated release page; it was pointing to a slightly older one. Thanks for the heads up!
