### ISSUE TITLE
keyboard shortcuts issue

### ISSUE THREAD

**Issue by loopernow** [rtiangha/SiEd-Dana#2]
I'm finding some issues with keyboard shortcuts.

Using the command-a and command-e shortcuts to go to the beginning and end of a line returns an 'a' and an 'e' each time the applicable shortcut is invoked. For example, if I pressed command-a and command-e on a line that said "This is a test line." the result would look like this:

eThis is a test line.a

Undo, cut and copy don't work by keyboard shortcut.

**Comment by rtiangha** [comment]
Sorry for the delay. I lost my dev environment when my laptop suffered a hard drive crash years ago and lost everything Palm OS related so unfortunately, I can't work on this project anymore.

That said, this program would inherit any bugs that were present in the original SiEd so if these keyboard bugs were there, then they'd be here too. Else, it could be due to different key codes introduced by the Dana's keyboard, but even if that were the case, I don't currently have a way to fix it. Sorry!
